# .golangci.yaml
# GolangCI-Lint configuration following 2024 best practices

run:
  timeout: 5m
  tests: true
  concurrency: 4

issues:
  # Exclude directories that are not part of your source code.
  exclude-dirs:
    - vendor
    - third_party
    - bazel-bin
    - bazel-out
    - bazel-testlogs
  # Exclude files such as generated files.
  exclude-files:
    - ".*_generated.go"
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false

linters:
  enable-all: true
  disable:
    - exportloopref


linters-settings:
  govet:
    # Enable shadow checking (replacing the deprecated check-shadowing).
    shadow: true
